name: Build

on:
    workflow_dispatch:

env:
    FORCE_COLOR: true

permissions:
    contents: write

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm build --standalone

            - name: Generate plugin list
              run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

            - name: Clean up obsolete files
              run: rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

            - name: Get some values needed for the release
              id: release_values
              run: echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Set up Git
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create new branch
              run: |
                  git checkout -b $RELEASE_TAG
                  git push -u origin $RELEASE_TAG
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ env.release_tag }}

            - name: Create and upload new release
              run: gh release create $RELEASE_TAG dist/* --title "Build $RELEASE_TAG" --notes "This is a build for $RELEASE_TAG"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ env.release_tag }}
